DROP TABLE IF EXISTS item CASCADE;
CREATE TABLE item (
  id        BIGINT  GENERATED BY DEFAULT AS IDENTITY,
  item_name VARCHAR(10),
  price     INTEGER,
  quantity  INTEGER,
  PRIMARY KEY (id)
);

-- test/resources/schema.sql 로 만들어야 함. 규칙임. => 스프링이 자동으로 해당 sql 문 실행해줌.
-- => DB 임베디드 모드에서 따로 테이블 안만들어줘도 됨
-- 그럼 테스트할 때, 이거 먼저 실행해서 테이블 만들어주고 해당 테스트 돌려줌